-- Remover a tabela se já existir
DROP TABLE IF EXISTS USUARIO;

-- Criar a tabela
CREATE TABLE USUARIO (
    ID_USUARIO BIGINT AUTO_INCREMENT PRIMARY KEY,
    USUARIO VARCHAR(255) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    DATA_ALTERACAO DATE NOT NULL,
    HORA_ALTERACAO TIME NOT NULL,
    DATA_CADASTRO DATE NOT NULL,
    STATUS VARCHAR(255) NULL
);

-- Inserir dados iniciais
INSERT INTO USUARIO (USUARIO, SENHA, EMAIL, DATA_ALTERACAO, HORA_ALTERACAO, DATA_CADASTRO, STATUS)
VALUES ('ADMIN', '{bcrypt}$2a$10$5uKS72zKjcW5vQMMM3hZY.Lb4L7J7jZ8T7WYk6tC6d6wV1sY6WQ0K', 'admin@admin.com',
        '2021-04-16', '11:25:09', '2021-04-16', 'ATIVO');