/****** Object:  Table [DBO].[USUARIO]    Script Date: 16/12/2020 15:49:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('DBO.USUARIO', 'U') IS NOT NULL
	DROP TABLE DBO.USUARIO;
GO

CREATE TABLE [DBO].[USUARIO](
	[ID_USUARIO] [bigint] IDENTITY(1,1) NOT NULL,
	[USUARIO] [varchar](255) NOT NULL,
	[SENHA] [varchar](255) NOT NULL,
	[EMAIL] [varchar](255) NOT NULL,
	[DATA_ALTERACAO] [date] NOT NULL,
	[HORA_ALTERACAO] [time](7) NOT NULL,
	[DATA_CADASTRO] [date] NOT NULL,
	[STATUS] [varchar](255) NULL
CONSTRAINT [PK_ID_USUARIO] PRIMARY KEY CLUSTERED
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_USUARIO] UNIQUE NONCLUSTERED 
(
	[USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT INTO USUARIO(USUARIO, SENHA, EMAIL, DATA_ALTERACAO, HORA_ALTERACAO, DATA_CADASTRO, STATUS)
VALUES ('ADMIN', '$2a$10$1XAxs1QFXZb.zAHsZ..rFONL8g18vWB8HI3xu8V.nH/JmT9m2QzE2', 'admin@admin.com', '2021-04-16', '11:25:09.2533333', '2021-04-16', 'ATIVO') GO