-- Remover a tabela se já existir
DROP TABLE IF EXISTS USUARIO;

-- Criar a tabela
CREATE TABLE USUARIO (
    ID_USUARIO BIGINT AUTO_INCREMENT PRIMARY KEY,
    USUARIO VARCHAR(255) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    DATA_ALTERACAO DATE NOT NULL,
    HORA_ALTERACAO TIME NOT NULL,
    DATA_CADASTRO DATE NOT NULL,
    STATUS VARCHAR(255) NULL
);

-- Inserir dados iniciais
INSERT INTO USUARIO (USUARIO, SENHA, EMAIL, DATA_ALTERACAO, HORA_ALTERACAO, DATA_CADASTRO, STATUS)
VALUES ('ADMIN', '$2a$10$ldbPqWR9SgC/G4.NPoIBVe1kVmfXS.lcWavZN3eIyysdbAN1hxAWi', 'admin@admin.com',
        '2021-04-16', '11:25:09', '2021-04-16', 'ATIVO');