-- Remover a tabela se já existir
DROP TABLE IF EXISTS PERFIS;

-- Criar a tabela
CREATE TABLE PERFIS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(255) NOT NULL UNIQUE
);

-- Inserir dados iniciais
INSERT INTO PERFIS (DESCRICAO) VALUES ('ADMIN');
INSERT INTO PERFIS (DESCRICAO) VALUES ('PRODUTO');
INSERT INTO PERFIS (DESCRICAO) VALUES ('PEDIDOS');