/****** OBJECT:  TABLE [DBO].[USUARIOS_TEM_PERFIS]    SCRIPT DATE: 13/01/2021 15:13:39 ******/
DROP TABLE IF EXISTS USUARIOS_TEM_PERFIS;
CREATE TABLE USUARIOS_TEM_PERFIS (
  USUARIO_ID BIGINT NOT NULL,
  PERFIL_ID BIGINT NOT NULL,
  PRIMARY KEY (USUARIO_ID, PERFIL_ID),
  CONSTRAINT FK_USUARIO_TEM_PERFIL_ID FOREIGN KEY (PERFIL_ID) REFERENCES PERFIS (ID),
  CONSTRAINT FK_PERFIL_TEM_USUARIO_ID FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID_USUARIO)
)
GO
INSERT INTO USUARIOS_TEM_PERFIS(USUARIO_ID, PERFIL_ID) VALUES (1, 1) GO