/****** OBJECT:  TABLE [DBO].[PRODUTO]    SCRIPT DATE: 16/04/2021 12:15 ******/
CREATE TABLE PRODUTO (
  ID_PRODUTO BIGINT IDENTITY(1,1) NOT NULL,
  CODIGO VARCHAR(255) NOT NULL UNIQUE,
  NOME VARCHAR(255) NOT NULL,
  UN_MEDIDA VARCHAR(6) NOT NULL,
  QUANTIDADE DECIMAL(10,4) NOT NULL,
  VALOR DECIMAL(10,4) NOT NULL,
  [STATUS] VARCHAR(255) NOT NULL,
  DATA_CADASTRO DATE NOT NULL,
  USUARIO_CADASTRO VARCHAR(255) NOT NULL,
  DATA_ALTERACAO DATE NOT NULL,
  HORA_ALTERACAO time(7) NOT NULL,
  USUARIO_ALTERACAO VARCHAR(255) NOT NULL,
  DESCRICAO TEXT NOT NULL,
  PRIMARY KEY (ID_PRODUTO)
)