-- Remover a tabela se já existir
DROP TABLE IF EXISTS UNIDADE_MEDIDA;

-- Criar a tabela
CREATE TABLE UNIDADE_MEDIDA (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SIGLA VARCHAR(255) NOT NULL UNIQUE,
    DESCRICAO VARCHAR(255) NOT NULL UNIQUE
);