/****** OBJECT:  TABLE [DBO].[UNIDADE_MEDIDA]    SCRIPT DATE: 26/04/2021 16:30 ******/
CREATE TABLE UNIDADE_MEDIDA (
  ID BIGINT IDENTITY(1,1) NOT NULL,
  SIGLA VARCHAR(255) NOT NULL UNIQUE,
  DESCRICAO VARCHAR(255) NOT NULL UNIQUE,
  PRIMARY KEY (ID)
)