-- Remover a tabela se já existir
DROP TABLE IF EXISTS CLIENTE;

-- Criar a tabela
CREATE TABLE CLIENTE (
    ID_CLIENTE BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    CNPJ VARCHAR(255) NOT NULL,
    DATA_CADASTRO DATE NOT NULL,
    DATA_ALTERACAO DATE NOT NULL,
    HORA_ALTERACAO TIME NOT NULL
);