/****** OBJECT:  TABLE [DBO].[CLIENTE]    SCRIPT DATE: 07/07/2021 13:11 ******/
CREATE TABLE CLIENTE (
  ID_CLIENTE BIGINT IDENTITY(1,1) NOT NULL,
  NOME VARCHAR(255) NOT NULL,
  CNPJ VARCHAR(255) NOT NULL,
  DATA_CADASTRO DATE NOT NULL,
  DATA_ALTERACAO DATE NOT NULL,
  HORA_ALTERACAO DATE NOT NULL,
  PRIMARY KEY (ID_CLIENTE)
)